eexport const environment = {
  production: true,
  apiUrl: 'http://localhost:3000',
  context: '/gfbio',
  searchUrl: '/search',
  semSearchUrl: '/semantic-search',
  suggestUrl: '/suggest',
  basketUrl: '/basket',
  imagePath: 'assets/img/',
  vatImg: 'vat.png',
  semSearchImg: 'icon_semsearch3.png',
  textAlertBasketErrorDownload: 'An error occured during the download.\nPlease contact the administrator for more information.',
  textTooltipBasketVATvisualizable: 'dataset can be visualized in VAT',
  textTooltipBasketVATnotVisualizable: 'dataset can not be visualized in VAT',
  textTooltipBasketDataAvailable: 'data are available for download',
  textTooltipBasketDataNotAvailable: 'data are not available for download',
  textTooltipBasketMetadataAvailable: 'metadata are available for download',
  textTooltipBasketMetadataNotAvailable: 'metadata are not available for download',
  textTooltipBasketMultimediaAvailable: 'multimedia are available for download',
  textTooltipBasketMultimediaNotAvailable: 'multimedia are not available for download',
  textTooltipBasketRemove: 'remove dataset from basket',
  textTooltipBasketEmpty: 'Please select a dataset from the search result.'
};